# Generated by Django 3.2.5 on 2022-11-01 09:23

from django.db import migrations, models
import group.models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_members', jsonfield.fields.JSONField(default={'group_members': []})),
                ('group_data', jsonfield.fields.JSONField(default={'group_data': []})),
                ('image', models.ImageField(blank=True, null=True, upload_to=group.models.Group_Log.nameFile)),
            ],
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('user_company', models.CharField(max_length=100)),
            ],
        ),
    ]
