# Generated by Django 3.2.5 on 2022-11-01 10:19

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_remove_user_data_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='groups',
            field=jsonfield.fields.JSONField(default={'groups': []}),
        ),
    ]
