# Generated by Django 3.2.5 on 2022-11-01 13:40

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_user_data_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_log',
            name='combined_shares',
            field=jsonfield.fields.JSONField(default={'combined_shares': []}),
        ),
        migrations.AddField(
            model_name='user_data',
            name='current_shares',
            field=jsonfield.fields.JSONField(default={'shares': []}),
        ),
    ]
