# Generated by Django 3.2.5 on 2022-11-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_group_log_members_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_log',
            name='image_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
