# Generated by Django 3.2.5 on 2022-11-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_group_log_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_log',
            name='image_url',
            field=models.CharField(default='', max_length=300),
        ),
    ]
