# Generated by Django 3.2.5 on 2022-11-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_group_log_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_log',
            name='key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
