# Generated by Django 3.2.5 on 2022-11-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_group_log_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_log',
            name='iv',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
