# Generated by Django 3.2.5 on 2022-11-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0010_auto_20221108_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='group_log',
            name='nonce',
            field=models.CharField(default='', max_length=300),
        ),
    ]
