# Generated by Django 3.2.5 on 2022-11-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0012_alter_group_log_nonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_log',
            name='nonce',
            field=models.TextField(max_length=256),
        ),
    ]
